### ISSUE TITLE
Usuarios

### ISSUE THREAD

**Issue by fdvj** [adoptapanama/admin-api#7]
# Prerequisitos

- [x] El componente de ACL debe estar listo para los permisos #4 
- [ ] El componente de correos debe estar listo #8
- [ ] El componente de organizaciones debe estar listo #9 
- [ ] El componente de roles debe estar listo #5 

# Requisitos
- [x] Como usuario con el permiso `users:list` debo ser capaz de ver la lista de usuarios en mi organización. `GET /users`

- [x] Como super usuario debo ser capaz de ver todos los usuarios del sistema `GET /users`

- [ ] Como usuario con el permiso `users:create` debo ser capaz de crear nuevos usuarios en la organización en la que estoy loggeado y asignarle un rol (obligatorio asignar un rol) `POST /users`

- [ ] Como super usuario debo ser capaz de crear usuarios y asignarles un rol dentro de cualquier organización o no asignarles un rol y solo invitarlos al sistema. `POST /users`

- [ ] Como super usuario debo ser capaz de crear otros super usuarios. `POST /users`

- [ ] Como usuario con el permiso `users:update`, debo ser capaz de actualizar un usuario siempre y cuando este sea miembro de mi organización solamente. **Si es miembro de otra organización**, no puedo editarlo. `PUT /users/{userId}`

- [ ] Como super usuario debo ser capaz de editar cualquier usuario de cualquier organización. `PUT /users/{userId}`

- [ ] Como usuario con el permiso `users:view` debo ser capaz de ver los detalles de un usuario dentro de mi organización. `GET /users/{userId}`

- [ ] Como super usuario debo ser capaz de ver detalles de cualquier usuario en cualquier organización.

- [ ] Como usuario con el permiso de `users:delete` debo ser capaz de eliminar a un usuario de mi organización, y en caso de que no perteneza a ninguna otra organización, eliminarlo del sistema (ver notas sobre eliminar usuario) `DELETE /users/{userId}`

- [ ] Como super usuario debo ser capaz de eliminar cualquier usuario del sistema (ver notas sobre eliminar usuario) `DELETE /users/{userId}`

- [ ] Como usuario debo ser capaz de aceptar una invitación y setear mi contraseña `POST /users/{userId}/confirm`

- [ ] Como usuario invitado a una organización, debo ser capaz de aceptar la invitación `POST /organizations/{organizationId}/users/{userId}/confirm`

# Notas 

- Cuando se crea un nuevo usuario, se envia una invitación al correo del usuario para que este confirme el proceso y se una a la organización. Mientras no se confirme, un flag de active en el usuario estará en `false`.
- Si el usuario ya existe pero en otra organización, no se crea un nuevo usuario, sino que se envía una invitación para que el usuario acepte unirse o no a la organización.
- Cuando es primer usuario, en su email recibe un correo con un token para finalizar la creación. Cuando este haga click en el token, se le debe preguntar qué contraseña usar para el usuario. Aqui se envia al BE mediante POST el token y la contraseña, y se guarda el usuario. El token se elimina pues es de un único uso y el usuario se cambia a active: true.
- Cuando el usuario existe en el sistema, se le envia una correo con un token de invitación para unirse a la organización. El token se envía mediante POST al BE para confirmar que el usuario aceptó la invitación de la organización
- Cuando el usuario ya existe en el sistema y la organización, debe tirar un error. Si la organización está deshabilitada, debe tirar un 404.
- Eliminar un usuario no significa borrarlo del sistema, sino deshabilitarlo y cambiar el email a `null`.
